name: Cleanup pr mirror branch

on:
  pull_request:
    types: [closed]
    branches:
        - current

permissions:
  contents: write

jobs:
  call-delete-branch:
    uses: vyos/.github/.github/workflows/cleanup-mirror-pr-branch.yml@T6967-add-mirror-workflows
    secrets: inherit
