name: Create Mirror PR and Repo Sync (Current)
on:
  pull_request_target:
      types:
        - closed
      branches:

permissions:
  pull-requests: write
  contents: write
jobs:
  mirror-pr-current:
    name: Mirror PR (Current)
    uses: ./.github/workflows/mirror-pr-current.yml
    secrets: inherit

  repo-sync-current:
    name: Repo Sync (Current)
    uses: ./.github/workflows/repo-sync-current.yml
    needs: [mirror-pr-current]
    secrets: inherit
