name: Create Mirror PR

on:
    pull_request_target:
      types:
        - closed
      branches:
        - current
    workflow_dispatch:
      inputs:
        pr_title:
          description: 'Title of the PR'
          required: true
        pr_number:
          description: 'Number of the PR'
          required: true

env:
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  Mirror-PR:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set vars
      run: |
        source_repo="${{ github.repository }}"
        echo "source_repo=${source_repo}" >> $GITHUB_ENV
        target_repo=$(echo $source_repo | sed 's/^[^\/]*\//vyos-networks\//')
        echo "target_repo=${target_repo}" >> $GITHUB_ENV
        pr_source_branch=$(git branch --show-current)
        echo "pr_source_branch=${pr_source_branch}" >> $GITHUB_ENV
        echo "pr_target_branch=${pr_source_branch}" >> $GITHUB_ENV
        pr_number=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number || github.event.pull_request.number }}
        echo "pr_number=${pr_number}" >> $GITHUB_ENV
        pr_title="${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr_title || github.event.pull_request.title }}"
        echo "pr_title=${pr_title}" >> $GITHUB_ENV
        echo "pr_merge_branch=mirror/current/$pr_number" >> $GITHUB_ENV

    - name: Get PR last commit
      run: |
        mkdir -p /tmp/public
        cd /tmp/public
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git init
        git remote add origin https://github.com/${source_repo}.git
        git fetch
        git checkout -b $pr_source_branch
        pr_info=$(gh pr view $pr_number --json commits)
        last_commit=$(echo $pr_info | jq -r '.commits[-1].oid')
        echo "last_commit=${last_commit}" >> $GITHUB_ENV

    - name: Create merge branch from last commit
      run: |
        cd /tmp/public
        git checkout -b $pr_merge_branch $last_commit

    - name: Push merge branch to target repo
      run: |
        cd /tmp/public
        git remote add target https://x-access-token:${{ secrets.PAT }}@github.com/${target_repo}.git
        git push target $pr_merge_branch

    - name: Create PR from merge branch to target branch
      run: |
        gh pr create --repo ${target_repo} --head $pr_merge_branch --base $pr_target_branch --title "${pr_title}" --body "Automated PR from $pr_merge_branch to $pr_target_branch"T
