name: Repo-sync by commit

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'source_repo'
        required: true
        type: string
      source_commit_sha:
        description: 'source_commit_sha'
        required: true
        type: string
      destination_branch:
        description: 'destination_branch'
        required: false
        default: 'current'
        type: string
  repository_dispatch:
    types: [sync-request]

permissions:
  contents: write

jobs:
  call-repo-sync-commit:
    uses: vyos/.github/.github/workflows/repo-sync-by-commit.yml@T6967-add-mirror-workflows
    secrets: inherit
    with:
      source_repo: ${{ inputs.source_repo }}
      source_commit_sha: ${{ inputs.source_commit_sha }}
      destination_branch: ${{ inputs.destination_branch }}
