name: Repo-sync (Current)

on:
    workflow_call:
    workflow_dispatch:

jobs:
  trigger-repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Bullfrog Secure Runner
        uses: bullfrogsec/bullfrog@v0
        with:
          egress-policy: audit

      - name: Trigger sync workflow
        shell: bash
        run: |
          echo "Triggering sync workflow for ${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REPO }}"
          echo "Triggering sync workflow with PAT ${{ secrets.PAT }}"
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REPO }}/actions/workflows/repo-sync-current.yml/dispatches \
            -d '{"ref":"git-actions"}'
