name: Trigger PR

on:
    pull_request_target:
      types:
        - closed
      branches:
        - current

jobs:
  trigger-PR:
    uses: vyos/.github/.github/workflows/trigger-pr.yml@current
    with:
      source_branch: 'current'
      target_branch: 'current'
    secrets:
      REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
      REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
      PAT: ${{ secrets.PAT }}
